spring:
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    
activemq:
  clientID: tuto-jms-spring-receiver
  queue:
    textMessage: text-destination
    objectMessage: object-destination
    
    