spring:
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin

server:
  port: 8081
    

#Propiedades de  configuracion para el Message Broker
jms:
  cache:
    size: 10
  clientid:
    topic: tuto-jms-spring-topic
    queue: tuto-jms-spring-queue
     
  topic:
    textMessage: text-destination
    
  queue:
    objectMessage: object-destination
    resendObjectMessaje : resend-object-destination
    
    